### ISSUE TITLE
TMC2209 V3 FYTECH UART

### ISSUE THREAD

**Issue by EPDCenter** [le3tspeak/Marlin-2.0.X-Sapphire-PRO#2]
Hi, could you explain how to connect X, Y, Z, E0 in UART mode, please?

**Comment by EPDCenter** [comment]
Is a 1K ohm resistor necessary? Many thanks for your time

**Comment by le3tspeak** [comment]
https://github.com/le3tspeak/Marlin-2.0.X-Sapphire-PRO/issues/1
